#ifndef CONSTANTS_H
#define CONSTANTS_H

#define COL_MAX 50
#define ROW_MAX 24

#define STARTING_BACKGROUND_X 2
#define STARTING_BACKGROUND_Y 1

#define MAX_WINDOWS 7

#define MAX_OBSTACLES 20
#define MAX_COLLECTIBLE_NUMBER 20
#define STARTING_ENEMY_NUMBER 1
#define ENEMY_NUMBER_CAP 10

#define BACKGROUND_COLOR_PAIR 1
#define BORDER_COLOR_PAIR 2
#define PLAYER_COLOR_PAIR 3
#define COLLECTIBLE_COLOR_PAIR 4
#define ENEMY_COLOR_PAIR 5
#define OBSTACLE_COLOR_PAIR 6

#define ROW_BORDER_CONTROL ROW_MAX - 1
#define COL_BORDER_CONTROL COL_MAX - 2

#define PLACEMENT_Y ROW_MAX - 2
#define PLACEMENT_Y_CONTROL 1
#define PLACEMENT_X COL_MAX - 6
#define PLACEMENT_X_CONTROL 3

#define MIN_PLAYER_X 2
#define MAX_PLAYER_X COL_MAX - 3
#define MIN_PLAYER_Y 1
#define MAX_PLAYER_Y ROW_MAX - 2

#endif //CONSTANTS_H
